export const ADMIN_API_ROUTES = {
  LOGIN: "cpanel/login",
  GET_CATEGORIES: "cpanel/categories",
  CREATE_CATEGORIES: "cpanel/categories",
  GETBYID_CATEGORIES: "cpanel/categories",
  UPDATE_CATEGORIES: "cpanel/categories",
  DELETE_CATEGORIES: "cpanel/categories",
  GET_PRODUCTS: "cpanel/products",
  CREATE_PRODUCTS: "cpanel/products",
  GETBYID_PRODUCTS: "cpanel/products",
  UPDATE_PRODUCTS: "cpanel/products",
  DELETE_PRODUCTS: "cpanel/products",
  GET_SIZES: "cpanel/sizes",
  CREATE_SIZES: "cpanel/sizes",
  GETBYID_SIZES: "cpanel/sizes",
  DELETE_SIZES: "cpanel/sizes",
  MEDIA_UPLOAD: "api/media/upload",

  GET_ORDER: "cpanel/orders",
  GET_ORDER_DETAILS: "/cpanel/orders", //{ID}
  CREATE_ORDER_SHIPMENT: (orderId) => `cpanel/orders/${orderId}/shipment/create`,
  CANCEL_ORDER_SHIPMENT: (orderId) => `cpanel/orders/${orderId}/shipment/cancel`,
  DOWNLOAD_ORDER_SHIPMENT_LABEL: (orderId) => `cpanel/orders/${orderId}/shipment/label`,

  GET_BANNERS: "cpanel/banners",
  CREATE_BANNERS: "cpanel/banners",
  GETBYID_BANNERS: "cpanel/banners",
  DELETE_BANNERS: "cpanel/banners",
  GET_WEB_SETTINGS: "cpanel/web-settings",
  UPDATE_WEB_SETTINGS: "cpanel/web-settings",
  GET_USERS: "cpanel/users",
  BAN_USER: (userId) => `cpanel/users/${userId}/ban`,
  UNBAN_USER: (userId) => `cpanel/users/${userId}/unban`,
};
