export const ADMIN_API_ROUTES = {
  LOGIN: "cpanel/login",
  GET_CATEGORIES: "cpanel/categories",
  CREATE_CATEGORIES: "cpanel/categories",
  GETBYID_CATEGORIES: "cpanel/categories",
  UPDATE_CATEGORIES: "cpanel/categories",
  DELETE_CATEGORIES: "cpanel/categories",
  GET_PRODUCTS: "cpanel/products",
  CREATE_PRODUCTS: "cpanel/products",
  GETBYID_PRODUCTS: "cpanel/products",
  UPDATE_PRODUCTS: "cpanel/products",
  DELETE_PRODUCTS: "cpanel/products",
  GET_SIZES: "cpanel/sizes",
  CREATE_SIZES: "cpanel/sizes",
  GETBYID_SIZES: "cpanel/sizes",
  DELETE_SIZES: "cpanel/sizes",
  MEDIA_UPLOAD: "api/media/upload",

  GET_ORDER: "cpanel/orders",
  GET_ORDER_DETAILS: "/cpanel/orders", //{ID}
  CREATE_ORDER_SHIPMENT: (orderId) => `cpanel/orders/${orderId}/shipment/create`,
  CANCEL_ORDER_SHIPMENT: (orderId) => `cpanel/orders/${orderId}/shipment/cancel`,
  DOWNLOAD_ORDER_SHIPMENT_LABEL: (orderId) => `cpanel/orders/${orderId}/shipment/label`,
  BULK_DOWNLOAD_ORDER_SHIPMENT_LABELS: "cpanel/orders/shipment/labels/bulk",

  GET_RETURN_ORDERS: "cpanel/order-returns",
  PAY_RETURN_REFUND: (orderId) => `cpanel/orders/${orderId}/return/refund`,

  GET_BANNERS: "cpanel/banners",
  UPDATE_BANNERS: "cpanel/banners",
  GET_WEB_SETTINGS: "cpanel/web-settings",
  UPDATE_WEB_SETTINGS: "cpanel/web-settings",
  GET_SCRATCH_CARD_SETTINGS: "cpanel/scratch-card-settings",
  UPDATE_SCRATCH_CARD_SETTINGS: "cpanel/scratch-card-settings",
  GET_SCRATCH_CARD_COUPONS: "cpanel/scratch-card-coupons",
  CREATE_SCRATCH_CARD_COUPONS: "cpanel/scratch-card-coupons",
  GETBYID_SCRATCH_CARD_COUPONS: "cpanel/scratch-card-coupons",
  UPDATE_SCRATCH_CARD_COUPONS: "cpanel/scratch-card-coupons",
  DELETE_SCRATCH_CARD_COUPONS: "cpanel/scratch-card-coupons",
  GET_USERS: "cpanel/users",
  BAN_USER: (userId) => `cpanel/users/${userId}/ban`,
  UNBAN_USER: (userId) => `cpanel/users/${userId}/unban`,

  DASHBOARD_PAYMENT_METHOD_DISTRIBUTION: "cpanel/dashboard-payment-method-distribution",
  DASHBOARD_TOTAL_CUSTOMERS: "cpanel/dashboard-total-customers",
  DASHBOARD_MONTHLY_SALES: "cpanel/dashboard-monthly-sales",
  DASHBOARD_TOP_PRODUCTS: "cpanel/dashboard-top-products",
  DASHBOARD_GENDER_DISTRIBUTION: "cpanel/dashboard-gender-distribution",
  DASHBOARD_MONTHLY_ORDER_STATUS: "cpanel/dashboard-monthly-order-status",
};
